version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    environment:
      # Variables de entorno para el servidor
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000

      # Firebase Admin SDK (solo servidor)
      - FIREBASE_PROJECT_ID=minijuegos-1012b
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@minijuegos-1012b.iam.gserviceaccount.com
      - FIREBASE_PRIVATE_KEY=|
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpemCTexEshBud
        lUPl3G/KuHgIkkg0M1jDSJw4BMpdeaNW2k25mEgCtWTZ3rI7Qs2kBSXYN4CQjVF1
        SRH2CATE9GP7AoGamcQ3sLHv8NPn5LWcZTzCtNaWtdLL4jxZtzyPrY441ENx0fRv
        bZzNUQQ42wlSE1nLrFshqEys2WeuXmvzGaic3stL4XsZbRVuMvTmRTQCqmkdO4fy
        9Kk89573uUrmZs38e9HbTgFFl0B7caVpJQibA8bhz99NI147aZ6aVvHot+/43dGt
        V4WV+hfPLZSjjmbJYdjMhQfN2F7J43rkOTuC5/0B4S9JrLdtwLFn9XFN8386ejdh
        Ev9WPyDX
        -----END PRIVATE KEY-----

      # Variables públicas de Firebase (cliente)
      - NUXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAkbQHYgQ_LiKgM5ZFe9b6HwY0POCOxn9c
      - NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=minijuegos-1012b.firebaseapp.com
      - NUXT_PUBLIC_FIREBASE_PROJECT_ID=minijuegos-1012b
      - NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=minijuegos-1012b.appspot.com
      - NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1075621373675
      - NUXT_PUBLIC_FIREBASE_APP_ID=1:1075621373675:web:33b4a9ebe8913edf387ec5
      - NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XXXXXXXXXX

      # API keys
      - RESEND_API_KEY=re_Ka1aZdkV_5knNdLCvQCXiptfUcqxyZTJ9

      # Configuración de host virtual
      - VIRTUAL_HOST=gamecraft.cl,www.gamecraft.cl
      - VIRTUAL_PORT=3000
    volumes:
      - .env:/app/.env
    restart: always
